# config/test.param.yaml
---
  lidar_top:
    filter_transform_lidar_top:
      ros__parameters:
        timeout_ms:       110
        raw_topic:       "points"
        filtered_topic:  "points_transformed"
        pcl_size:         256000
        input_frame_id:  "lidar_top"
        output_frame_id: "base_link"
        init_timeout_ms:  5000
        expected_num_subscribers: 1
        expected_num_publishers:  1
        start_angle:            0.0       # radians
        end_angle:              6.28
        min_radius:             3.0      # meters
        max_radius:             55.0
        static_transformer:
          quaternion:
            x:                    0.0
            y:                    0.0
            z:                    0.0
            w:                    1.0
          translation:
            x:                    1.6
            y:                    0.0
            z:                    1.2
